name: Ubuntu

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "10.0"
        directory: ${{ runner.temp }}/llvm

    - name: Install dependencies
      run: sudo apt-get install -y python3 python3-pip ruby ruby-dev rpm && sudo gem install --no-ri --no-rdoc fpm
    - name: Install python3 dependencies
      run: |
        export SETUPTOOLS_USE_DISTUTILS=stdlib
        python3 -m pip install --upgrade pip setuptools wheel
    - name: build alusus
      run:  |
        mkdir build && cd build
        cmake ../Sources/ -DCMAKE_BUILD_TYPE=Release -DLLVM_PATH=${{ runner.temp }}/llvm
        make -j $(nproc --all)
    - name:  automated tests alusus
      run:  |
        cd build && make test